title: Kulturpop
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7685285
  brandStrength: 0.9897959
  lightness: 0.4871106
  brandColors:
    - '#FCCC00'
    - '#F99300'
    - '#EF5108'
    - '#E0020D'
    - '#FEF9B8'
  rhythmicContrast: 0.4291085
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: kulturpop
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0.7932331
