name: kulturpop
favicon: null
layout_spectrum: 0.013579320861026645
typography_spectrum: 0.11400083010084927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.0967936972156167
  lightness: 0.6114940205588937
  saturation: 0.6140455610584468
  rhythmicContrast: 0.599969755159691
purpose: []
